### ISSUE TITLE
Bad Request deploying Threat Intelligence Solution for Azure Government ARM template in Azure Government

### ISSUE THREAD

**Issue by shaken1901** [Azure/Azure-Sentinel#11947]
**Describe the bug**
When deploying version 3.0.5 of the ARM template "Threat Intelligence Solution for Azure Government", an error is encountered with the message:  "The connector 'MicrosoftDefenderThreatIntelligence' is not supported in this environment"

**To Reproduce**
1. Deploy this ARM template in Azure Government:  https://raw.githubusercontent.com/Azure/Azure-Sentinel/79505203b5f48a228bc36ae99e85c66d66cc6baf/Solutions/Threat%20Intelligence%20Solution%20for%20Azure%20Government/Package/mainTemplate.json
2. See error

**Expected behavior**
Template should not attempt to deploy the unsupported data connector in the Azure US Government cloud, so that no such error is encountered.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A - can be reproduced in Azure Portal by deploying as a custom template.

**Smartphone (please complete the following information):**
N/A - can be reproduced in Azure Portal by deploying as a custom template.

**Additional context**
N/A

**Comment by v-visodadasi** [comment]
@shaken1901 , I wanted to let you know that I deployed the ARM template as a custom template in the Azure Portal, and the deployment completed successfully. It seems the issue with the MicrosoftDefenderThreatIntelligence connector not being supported in the Azure Government environment did not affect the deployment in my case.

Please let me know if there's anything specific you would like me to check or if you need further assistance.

**Comment by v-visodadasi** [comment]
@shaken1901 , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive response by the given date, we will close this issue.

**Comment by v-visodadasi** [comment]
@shaken1901, Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!

**Comment by shaken1901** [comment]
@v-visodadasi  -  apologies for my delayed response.  I would appreciate another look at this issue, as  I am still seeing an error when deploying the template in Azure Government.  In my case, the error was encountered when selecting US Government Virginia as the location.  All resources in the template deploy successfully except for the Data Connector, which returns this error message:

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "The connector 'MicrosoftDefenderThreatIntelligence' is not supported in this environment"
    }
  ]
}

My colleague reports the same error when deploying this template, so there's definitely something wrong.  Please let me know if there is additional information I can provide in support of your review.

**Comment by shaken1901** [comment]
Could someone with appropriate permissions please re-open this issue?
