### ISSUE TITLE
Microsoft Sentinel - JIRA connector REST API not working

### ISSUE THREAD

**Issue by jhn123-png** [Azure/Azure-Sentinel#12811]
Initially, I have a deployment failure with the same error message reported in issue 10983 
I saw an engineer suggesting redeploying the solution by using this [template ](https://[raw.githubusercontent.com/Azure/Azure-Sentinel/af1e2a30e4d3b8d57c09a1cd7f82825fd6f1c882/Solutions/AtlassianJiraAudit/Package/mainTemplate.json](https://raw.githubusercontent.com/Azure/Azure-Sentinel/af1e2a30e4d3b8d57c09a1cd7f82825fd6f1c882/Solutions/AtlassianJiraAudit/Package/mainTemplate.json)), which I already did. The deployment now is complete and I don't see any failure. However, I see this error message, which turns out to be different from the original one that I have
**Connector resource creation failed
Failed to create required resources for data connector LocationRequired: The location property is required for this definition.**

**Comment by v-sudkharat** [comment]
@ThanhNhan291204, Can you provide the screenshot which error your facing?

**Comment by jhn123-png** [comment]
@v-sudkharat Hi Sudkharat, here is the error

<img width="527" height="194" alt="Image" src="https://github.com/user-attachments/assets/fc073af8-1701-44a3-a562-eedad1b02b78" />

**Comment by v-sudkharat** [comment]
@ThanhNhan291204, The old issue was reported regarding connector connectivity has been already fixed.
Could you please let us know which solution version currently do have? 
You can also follow the below to resolve the error: 
1. If there is update available for solution, Kindly update existing the solution and try again. 
2. If solution is updated, and error still persist: 
Go to data connector blade and delete the existing CCF connector: 

<img width="1325" height="402" alt="Image" src="https://github.com/user-attachments/assets/a9b24de8-e0d2-47ff-95ab-1b1d6369dbc8" />

Then, Reinstall the existing solution from content hub: 

<img width="1126" height="449" alt="Image" src="https://github.com/user-attachments/assets/3b55ba69-5d70-4ceb-8c11-ab01455be6e2" />

And configure the connector, I got 404 as i enter the demo credentials, but as you have corrected one so connector status show as Connected: 

<img width="1198" height="526" alt="Image" src="https://github.com/user-attachments/assets/f0baa285-711b-45fb-b5a1-1d18fb335962" />

Please let us know if still have the same issue or the above steps helps you to unblock you. 

Many Thanks!

**Comment by jhn123-png** [comment]
1. I can confirm that I am the right update
2. I'll do it. 
Initially I faced the connectivity issue, which is not there after deploying the solution using this template https://raw.githubusercontent.com/Azure/Azure-Sentinel/af1e2a30e4d3b8d57c09a1cd7f82825fd6f1c882/Solutions/AtlassianJiraAudit/Package/mainTemplate.json
However, this time we have a new error message. By the way, I'll let you know when I'm done

**Comment by v-sudkharat** [comment]
@ThanhNhan291204, Ok

**Comment by jhn123-png** [comment]
<img width="1189" height="436" alt="Image" src="https://github.com/user-attachments/assets/bd2194d3-9fca-4942-aefa-e38b4d68c46d" />

<img width="244" height="171" alt="Image" src="https://github.com/user-attachments/assets/e511f1b8-b4a7-4c8c-9853-3cfba40ed549" />

Hi @v-sudkharat , good day, still the same error

**Comment by v-sudkharat** [comment]
@jhn123-png, Need to check in your environment, can you share mail id, so we can quick connect on this and check for the issue.

**Comment by v-sudkharat** [comment]
@jhn123-png, are you getting same error in another workspace as well? If possible, can you check once in other Region

**Comment by v-sudkharat** [comment]
@jhn123-png, waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @jhn123-png, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
