### ISSUE TITLE
Get-GitHubAuditEntry Creates Duplicate Log Entries

### ISSUE THREAD

**Issue by phenggeler** [Azure/Azure-Sentinel#1384]
**Describe the bug**
I have noticed that about every 10 minutes, I get duplicate log entries from the Get-GitHubAuditEntry logic app. The logic app is scheduled to run every 5 minutes, so it looks like every other run is causing duplicate logs to be written. For instance, below is an example in which every 10 minutes, the same repo.destroy action was written to log analytics. 

![image](https://user-images.githubusercontent.com/10621768/100770659-bd6e7b00-33ba-11eb-80d5-5b47a5bcd31a.png)

**To Reproduce**
1. Create the Get-GitHubAuditEntry logic app and corresponding Azure resources to run this process
2. Enable the logic app
3. Let the logic app run for about .5 hour to 1 hour
4. In log analytics, pick a specific log
5. Using KQL, query down to the at log. Note that the log will appear multiple times. 

**Expected behavior**
Each log should only be written once. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10621768/100770915-09212480-33bb-11eb-8725-0509d0ccccda.png)

**Additional context**
This might be a shot in the dark, but in looking at the logic app runs, I did notice that the Lastrun-Audit.json has an empty lastContext field every other run. 

For instance, below is the value of that lastrun-Audit.json after two separate logic app runs (one in which logs were written, and one in which logs were not written):

Value of lastrun-Audit.json after a Logic App run where logs were written:

`
{
  "lastRun": "2020-12-01T16:38:35.7034117Z",
  "lastContext": "X5Tcs12fJvW3"
}
`
Value of lastrun-Audit.json after a Logic App run where logs WERE NOT written:

`
{
  "lastRun": "2020-12-01T16:33:36.0510677Z",
  "lastContext": ""
}
`

**Comment by sreedharande** [comment]
@phenggeler - Fixed these issues with New connector using Azure Functions
https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GithubFunction

**Comment by phenggeler** [comment]
Thanks @sreedharande! I will give it a shot

**Comment by phenggeler** [comment]
@sreedharande - I have migrated over to using the function app solution (https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GithubFunction)

However, I am seeing an odd issue there. Every 10 minutes, the Function App writes 1 record to: "Github_CL". The record 'value' field appears to be the full array of Github audit logs. This appears to be wrong for the following reasons:

* I would expect every node action in the array to show up as a unique row in the Github_CL records (not just one big json array with all of the logs
* The same record (of the entire audit history) appears to be written to Sentinel every 10 minutes. 

`
[
  {
    "node": {
      "action": "repo.create",
      "actor": {},
      "actorIp": "*****************",
      "actorLocation": {
        "city": "*****************",
        "country": "*****************",
        "countryCode": "*****************",
        "region": "*****************",
        "regionCode": "*****************"
      },
      "actorLogin": "*****************",
      "actorResourcePath": "*****************",
      "actorUrl": "*****************",
      "createdAt": "2020-09-28T19:16:40.661Z",
      "operationType": "CREATE",
      "user": null,
      "userLogin": null,
      "userResourcePath": null,
      "forkParentName": null,
      "forkSourceName": "*****************",
      "organizationName": "*****************",
      "repositoryName": "*****************",
      "visibility": "INTERNAL"
    }
  },
.......
]
`
Are you aware of this issue? Is there a current ticket for that issue?

**Comment by sreedharande** [comment]
Hi @phenggeler,

- On each run we are getting all GitHub Audit logs as a single record - Where as Logic App puts them as a unique rows. We fixed this in Azure Function. This will change KQL Queries on Github_CL. Following is an example
`GitHub_CL 
| where TimeGenerated > ago(30d) 
| top 1 by TimeGenerated
| extend AuditEntries = todynamic(parse_json(value_s))
| mv-expand AuditEntries
| evaluate bag_unpack(AuditEntries)
| extend createdAt_ = tostring(parse_json(node).createdAt)
| extend action_ = tostring(parse_json(node).action) 
| extend userLogin_ = tostring(parse_json(node).userLogin)
| extend organizationName_ = tostring(parse_json(node).organizationName)
| extend TimeGenerated = createdAt_
| where action_ == "org.add_member" or action_ == "org.remove_member"
| extend MemberName = userLogin_
| extend Action = iif(action_=="org.add_member", "Added", "Removed")| extend Organization = organizationName_
| sort by TimeGenerated desc
| project MemberName, Action, Organization
`
- GitHubFunction is a TimerTrigger, it triggers every 5 mins, that's the reason you are seeing new record every 5/10 min
- Currently there is no way to update/configure timer schedule (cron expression)- will add this feature.

**Comment by phenggeler** [comment]
Thanks @sreedharande - that query you posted for me is not working for me. Any suggestions? Thanks for all of your help!

`
'extend' operator: Failed to resolve scalar expression named 'node'
If issue persists, please open a support ticket. Request id: 11c6b861-755f-4d17-a890-1cd9283394f6

`

**Comment by sreedharande** [comment]
@phenggeler - Please find the parser here https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/GitHubFunction/GitHubAuditLog.txt

Just deployed New Version of GitHub Function with the following Feature
- You can control Function App TimerTrigger Schedule by simply putting your own value in "Schedule" Environment Variable. By Default its 10 min
- Updated "lastrun-Audit.json" to support multiple org's
- Updated README.MD

Deploy new version from https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GithubFunction

**Comment by phenggeler** [comment]
Thanks @sreedharande but I am still getting this error when I run the query in the parser you shared. Can you validate that that parser is working for you? Also if it helps, when I look at 'AuditEntries' in the parser, it appears to be an array of objects that have 'node' at their base:
`
[
{
"node": {}
}, 
{
"node": {}
}
]
`


`
'project' operator: Failed to resolve scalar expression named 'node'
`

**Comment by sreedharande** [comment]
Thanks @phenggeler, Parser is working fine at my end. I am querying two Orgs Audit Logs. Can you please confirm your GitHub_CL custom log looks like as follows, do you see value_s with different nodes.

![image](https://user-images.githubusercontent.com/22670063/102674542-3a377e00-414b-11eb-803c-60bc91c50633.png)

If it is not in the above format, then I need to find the root cause. another user also reported the same issue.

**Comment by phenggeler** [comment]
Hi @sreedharande, I see a value_s with an array of different nodes, as you can see in the example below. But it is not in the format that you posted. 

![image](https://user-images.githubusercontent.com/10621768/102675368-555bbb00-4156-11eb-8685-a17c39a68d40.png)

**Comment by phenggeler** [comment]
Hi @sreedharande - just touching base on this. Is there a suggested workaround to the issue that appears to be affecting multiple users?

**Comment by sreedharande** [comment]
Hi @phenggeler - hope you had great holidays. Do you have some time this week, I would like to schedule call with you to troubleshoot this issue.

**Comment by phenggeler** [comment]
Hi @sreedharande - I hope you had a great holiday as well. I would be happy to schedule a call with you. What is the best way to connect? Could you private message your email to me in order to coordinate a call?

**Comment by phenggeler** [comment]
Hi @sreedharande - just touching base on this. I have some availability this week and next if you would like to schedule a time to troubleshoot

**Comment by phenggeler** [comment]
Hi @sreedharande - just following up on this. Would we be able to connect in the coming week or two? Thanks!

**Comment by sreedharande** [comment]
@phenggeler - Thanks for following up. I am unable to reach you, as your profile doesn't have your email id

**Comment by phenggeler** [comment]
Hi @sreedharande - please contact me here: peter.john.henggeler@gmail.com

**Comment by sreedharande** [comment]
Thanks @phenggeler - Sent couple of slots to connect

**Comment by sreedharande** [comment]
@phenggeler - Thanks for your time. Pushed latest changes to the GitHub Azure Function Data connector. Check it out and let me know if you any issues

**Comment by phenggeler** [comment]
Hi @sreedharande - I will work on getting this tested and let it run for a bit. Hopefully I will have more to report here shortly.

**Comment by phenggeler** [comment]
@sreedharande thanks this latest change worked! great job man :)
