### ISSUE TITLE
Reset-ADDUserPassword - Forbidden 403 from insufficient privileges

### ISSUE THREAD

**Issue by owilkins1** [Azure/Azure-Sentinel#9656]
I have deployed the Reset-ADDUserPassword playbook to an environment and I am having issues with permissions at the "HTTP - reset a password" stage of the logic app.

My app registration has a higher level of privilege permission granted "User.ReadWrite.All" but I seem to receive a "Forbidden 403" error.
 
```
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
```

Has anyone experienced this issue and found a resolution? Everything up to this point is working perfectly and I seemingly have the highest level privilege already granted so not sure on what this error is referring to.

I've seen on some other articles that passwords cannot be changed with application permissions. Could this be the cause? but then I wouldn't expect this playbook to exist if those articles were true.

Thanks

**Comment by v-muuppugund** [comment]
Hi @owilkins1 , Thanks for flagging this issue, we will investigate this issue and get back 	to you with some updates by 27Dec2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @owilkins1 ,Could you please check the following permissions
- Password Administrator (reset password for regular users)/Global Administrator (reset password for admins and regular users) and Microsoft Sentinel Responder permissions to the managed identity,

Please let me know if any issues or queries

**Comment by v-muuppugund** [comment]
Hi @owilkins1 ,Gentle Reminder,Could you please check the following permissions

Password Administrator (role in AAD ) and Microsoft Sentinel Responder permissions to the managed identity,
Please let me know if any issues or queries

**Comment by owilkins1** [comment]
> Hi @owilkins1 ,Gentle Reminder,Could you please check the following permissions
> 
> Password Administrator (role in AAD ) and Microsoft Sentinel Responder permissions to the managed identity, Please let me know if any issues or queries

Hi, thanks for coming back. I will check these details today and get back to you.

**Comment by Lisan86** [comment]
We got the same issue. and we set the Password Administrator (role in AAD ) and Microsoft Sentinel Responder permissions to the managed identity.

**Comment by owilkins1** [comment]
> We got the same issue. and we set the Password Administrator (role in AAD ) and Microsoft Sentinel Responder permissions to the managed identity.

and that solved your issue?

I haven't been able to test as I need to get an higher privileged admin to assign roles.

**Comment by Lisan86** [comment]
No, didn't work for us. :(.

**Comment by owilkins1** [comment]
> Hi @owilkins1 ,Gentle Reminder,Could you please check the following permissions
> 
> Password Administrator (role in AAD ) and Microsoft Sentinel Responder permissions to the managed identity, Please let me know if any issues or queries

Any additional things we can try?

**Comment by v-muuppugund** [comment]
Hi @Lisan86 / @owilkins1 ,Is admin consent is given to AAD app in the tenant,if needed we can have a teams meeting for further troubleshooting the issue.

**Comment by Lisan86** [comment]
Hi @v-muuppugund, yes, it's probably better if we have a Teams meeting

**Comment by v-muuppugund** [comment]
Hi @Lisan86 ,Could you please suggest convenient time slots to this email id i.e. (v-muuppugund@microsoft.com) for a team's meeting, so we can further troubleshoot the issue.

**Comment by v-muuppugund** [comment]
Hi @Lisan86 ,Call has been scheduled for tomorrow for further troubleshooting the issue

**Comment by v-muuppugund** [comment]
Hi @Lisan86 ,The issue has been resolved as discussed over call ,done the E2E troubleshooting and corrected the inputs and permissions in AAD and logic apps ,now logic app is up and running

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/c61f69e7-ed00-4264-8ac9-8b0691afa9e3)

we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9656) as issue resolved. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!

**Comment by owilkins1** [comment]
@Lisan86 Hi, glad you got it sorted on your end! 

Could you take some time to explain in further detail exactly what the issue was and your resolution?

**Comment by Lisan86** [comment]
@owilkins1 Hi, sure i try to help you.


First of all, we manually deleted all permissions for the Password Administrator role in AAD and Microsoft Sentinel Responder permissions for the managed identity. The next step was to check the IDs in the PowerShell script. There was a small mistake; we didn't change the Graph app ID. We corrected it to the Enterprise Application App ID. After this, we ran the PowerShell script again and checked the permissions.

The following step involved reviewing the logic in the Logic App Designer section, focusing on the HTTP Post method "Patch." We switched to the Enterprise Application App in AAD for the Logic App and set the permission using the link: https://entra.microsoft.com/#view/Microsoft_AAD_IAM/ManagedAppMenuBlade/~/Permissions/objectId/3fd68cf5-263c-4127-9475-80b027ccef94/appId/76d97eae-0bdd-4c48-8b54-6ee6265f1fed/preferredSingleSignOnMode~/null/servicePrincipalType/ManagedIdentity/fromNav/ Be sure to grant the following permission:

Application: User.ManageIdentities.All, User.EnableDisableAccount.All, User.ReadWrite.All, Directory.ReadWrite.All

After completing this step, we ran the Logic App again and did not encounter any errors.

Additionally, ensure that you do not test with a user who has a PIM role under any circumstances! Otherwise, it will not work unless you have granted the Logic App Global Admin rights.

**Comment by owilkins1** [comment]
> @owilkins1 Hi, sure i try to help you.
> 
> First of all, we manually deleted all permissions for the Password Administrator role in AAD and Microsoft Sentinel Responder permissions for the managed identity. The next step was to check the IDs in the PowerShell script. There was a small mistake; we didn't change the Graph app ID. We corrected it to the Enterprise Application App ID. After this, we ran the PowerShell script again and checked the permissions.
> 
> The following step involved reviewing the logic in the Logic App Designer section, focusing on the HTTP Post method "Patch." We switched to the Enterprise Application App in AAD for the Logic App and set the permission using the link: https://entra.microsoft.com/#view/Microsoft_AAD_IAM/ManagedAppMenuBlade/~/Permissions/objectId/3fd68cf5-263c-4127-9475-80b027ccef94/appId/76d97eae-0bdd-4c48-8b54-6ee6265f1fed/preferredSingleSignOnMode~/null/servicePrincipalType/ManagedIdentity/fromNav/ Be sure to grant the following permission:
> 
> Application: User.ManageIdentities.All, User.EnableDisableAccount.All, User.ReadWrite.All, Directory.ReadWrite.All
> 
> After completing this step, we ran the Logic App again and did not encounter any errors.
> 
> Additionally, ensure that you do not test with a user who has a PIM role under any circumstances! Otherwise, it will not work unless you have granted the Logic App Global Admin rights.

Hi, thanks for your comment.

So I've added all these permissions to my app registration and still receive the same forbidden error.

I'm not really sure what you are referring to with graph app id and powershell script. My logic app is functional until it tries to make a graph API call to reset the password.

I'm afraid I need some more information from yourself @Lisan86  or @v-muuppugund.

My managed identity does not have password administrator or responder role in AAD.

My app registration has all application permissions User.ManageIdentities.All, User.EnableDisableAccount.All, User.ReadWrite.All, Directory.ReadWrite.All granted with consent.

I'm not sure what you refer to with powershell script, maybe I am missing something but still forbidden only on the reset password stage.

**Comment by sahil-skyscend** [comment]
> Hi @Lisan86,The issue has been resolved as discussed over the call ,done the E2E troubleshooting and corrected the inputs and permissions in AAD and logic apps ,now logic app is up and running
> 
> ![image](https://private-user-images.githubusercontent.com/139563098/294498338-c61f69e7-ed00-4264-8ac9-8b0691afa9e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTU2ODUsIm5iZiI6MTcxNDExNTM4NSwicGF0aCI6Ii8xMzk1NjMwOTgvMjk0NDk4MzM4LWM2MWY2OWU3LWVkMDAtNDI2NC04YWM5LThiMDY5MWFmYTllMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwNzA5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzU3ODhhOGIzZGNjNGZjNmM0NjQ3MGY3YWI1OTMwYjAyOTJhMDU0NTJiNzVkNTJjMWUzNjk3MzJjNGZjYjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7PAs843G2-Y4c4gEHz2_t9QBAD27gy6H9W1t988BESs)
> 
> we are closing your issue (#9656) as issue resolved. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!

How can solve this issue can you please explain in brief?

**Comment by hemantkumar5151** [comment]
Hi @Lisan86 , @owilkins1 @v-muuppugund ,

I'm facing the same issue although we have assigned the password administrator and sentinel responder to system managed identify.

Your prompt help would be highly appreciated.
